title: Stephen Ma
description: "Personal website and portfolio showcasing my work and experiences"
url: "https://stema373.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Theme settings
theme: minima

# Site Author
author: Stephen Ma
email: sma9765625@gmail.com

# Social media
github_username: stema373
linkedin_username: stephenma888

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stema373"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      author_profile: true

# Exclude README.md from being processed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
